version: '3.4'

services:

  # webapi:
  #   container_name: cash-flow-api
  #   image: cash-flow-api
  #   build:
  #     context: .
  #     dockerfile: src/CashFlow.Api/Dockerfile
  #   ports:
  #     - 8000:80
  #     - 8001:443
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://+:443;http://+:80
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=dev@123
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #     - CONNECTIONSTRINGS__SQLSERVER=Server=host.docker.internal,1433;Initial Catalog=sql-nopaper-dev;User ID=sa;Password=#Agape@2020;Connection Timeout=30;
  #   volumes:
  #     - ~/.vsdbg:/remote_debugger:rw
  #     - ~/.aspnet/https:/https:ro
  #   depends_on:
  #     mssql:
  #       condition: service_healthy
  #   healthcheck:
  #     test: curl -k --fail https://localhost:443/healthz || exit 1
  #     interval: 5s
  #     timeout: 10s
  #     retries: 3

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: cash-flow-mssql
    environment:
      SA_PASSWORD: "Developer@1234"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-Usa",
          "-PDeveloper@1234",
          "-Q",
          "select 1"
        ]
      interval: 3s
      retries: 3
      timeout: 10s
